# Generated by Django 4.0.4 on 2022-05-06 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 28, 26, 286233, tzinfo=utc)),
        ),
    ]
