# Generated by Django 4.0.4 on 2022-05-09 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='disclosure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 8, 48, 15, 717767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 8, 48, 15, 717767, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ManyToManyField(to='blog.games'),
        ),
    ]
